"""生成模型子包的公共 API。

该子包独立导出 TaskGraph、Representation、TransitionKernel、CognitiveGraph、
Planning 和 CognitiveNavigationAgent 相关对象；不修改根包 ``cognitivemap.__init__``。
"""

from cognitivemap.generative_model.agent import CognitiveNavigationAgent
from cognitivemap.generative_model.cognitive_graph import (
    build_cognitive_graph,
    build_geometry_artifacts,
    compute_classical_mds,
    compute_directed_distances,
    symmetrize_distances,
)
from cognitivemap.generative_model.planning import expand_cognitive_path, plan_cognitive_path
from cognitivemap.generative_model.representations import (
    ChunkRepresentation,
    LandmarkRepresentation,
    PrimitiveRepresentation,
    RepresentationBuilder,
    RepresentationSpec,
    validate_representation,
)
from cognitivemap.generative_model.task import TaskGraph
from cognitivemap.generative_model.transition_kernel import (
    build_chunk_kernel,
    build_landmark_kernel,
    build_primitive_kernel,
    build_transition_kernel,
    validate_kernel,
    validate_kernel_support,
)
from cognitivemap.generative_model.types import (
    AStarResult,
    AStarStatus,
    ChunkToken,
    CognitiveEdge,
    CognitiveGraph,
    CognitiveNavigationError,
    CPDBlock,
    DirectedDistance,
    Embedding,
    EmbeddingError,
    ErrorDetail,
    ErrorStage,
    ExpansionCandidate,
    ExpansionError,
    ExpansionResult,
    ExpansionStatus,
    ExpansionTrace,
    Family,
    InvalidChunkRepresentationError,
    InvalidInputError,
    InvalidKernelError,
    InvalidLandmarkRepresentationError,
    InvalidPrimitiveRepresentationError,
    InvalidRepresentationError,
    InvalidTaskGraphError,
    InvalidTrialSpecError,
    KernelSupport,
    KernelSupportEntry,
    ModelArtifacts,
    PlanningConfig,
    PlanningError,
    PrimitiveToken,
    RunMetadata,
    RunResult,
    RunStatus,
    SerializationError,
    StateId,
    SupportKind,
    SymmetricDistance,
    TerminationRecord,
    TokenTrace,
    TransitionKernel,
    TrialSpec,
)

__all__ = [
    "StateId",
    "Family",
    "SupportKind",
    "CPDBlock",
    "RunStatus",
    "AStarStatus",
    "ExpansionStatus",
    "ErrorStage",
    "CognitiveNavigationError",
    "InvalidInputError",
    "InvalidTaskGraphError",
    "InvalidRepresentationError",
    "InvalidPrimitiveRepresentationError",
    "InvalidChunkRepresentationError",
    "InvalidLandmarkRepresentationError",
    "InvalidTrialSpecError",
    "InvalidKernelError",
    "EmbeddingError",
    "PlanningError",
    "ExpansionError",
    "SerializationError",
    "PrimitiveToken",
    "ChunkToken",
    "TokenTrace",
    "PlanningConfig",
    "TrialSpec",
    "KernelSupportEntry",
    "KernelSupport",
    "TransitionKernel",
    "CognitiveEdge",
    "CognitiveGraph",
    "DirectedDistance",
    "SymmetricDistance",
    "Embedding",
    "ModelArtifacts",
    "AStarResult",
    "ExpansionCandidate",
    "ExpansionTrace",
    "TerminationRecord",
    "ExpansionResult",
    "ErrorDetail",
    "RunMetadata",
    "RunResult",
    "TaskGraph",
    "PrimitiveRepresentation",
    "ChunkRepresentation",
    "LandmarkRepresentation",
    "RepresentationSpec",
    "RepresentationBuilder",
    "validate_representation",
    "build_transition_kernel",
    "build_primitive_kernel",
    "build_chunk_kernel",
    "build_landmark_kernel",
    "validate_kernel",
    "validate_kernel_support",
    "build_cognitive_graph",
    "compute_directed_distances",
    "symmetrize_distances",
    "compute_classical_mds",
    "build_geometry_artifacts",
    "plan_cognitive_path",
    "expand_cognitive_path",
    "CognitiveNavigationAgent",
]
